server:
  public_url: "http://127.0.0.1:8080"
  dev_listen_addr: "127.0.0.1:8080"
  http_listen_addr: ":80"
  https_listen_addr: ":443"
  dev_mode: true
  domain_names: ["auth.example.com"]
  tls:
    mode: "autocert"
    cache_dir: "./.certs"
    email: "ops@example.com"
    hsts_max_age: 15552000
    min_version: "1.2"
  trust_proxy_headers: true
  cors:
    client_origin_urls: ["http://localhost:3000"]
    allowed_headers: ["Authorization", "Content-Type"]
    allowed_methods: ["GET", "POST", "OPTIONS"]

keys:
  jwks_path: ""
  rotate_interval: "168h"
  alg: "RS256"

clients:
  - client_id: "webapp"
    client_secret: ""
    redirect_uris:
      - "http://127.0.0.1:3000/callback"
      - "http://127.0.0.1:8080/dev/callback"
    scopes: ["openid", "profile", "email", "ai.read", "ai.write"]
    audiences: ["ai-gateway"]

providers:
  default: "entra"
  auth0:
    issuer: ""
    client_id: ""
    client_secret: ""
  entra:
    issuer: "https://login.microsoftonline.com/common/v2.0"
    tenant_id: "YOUR_TENANT_ID"
    client_id: "ENTER_ENTRA_APP_CLIENT_ID"
    client_secret: "ENTER_ENTRA_APP_CLIENT_SECRET"

tokens:
  access_ttl: "10m"
  refresh_ttl: "720h"
  rotate_refresh: true
  audience_default: "ai-gateway"

sessions:
  ttl: "12h"
